# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_2708n6tos6\clone\recipe, last modified Fri Nov  4 14:52:18 2022
# ------------------------------------------------

package:
  name: openssl
  version: 1.1.1s
source:
  fn: openssl-1.1.1s.tar.gz
  sha256: c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa
  url: https://www.openssl.org/source/openssl-1.1.1s.tar.gz
build:
  binary_has_prefix_files: null
  detect_binary_files_with_prefix: true
  number: '0'
  run_exports:
    - openssl >=1.1.1s,<1.1.2a
  string: h2bbff1b_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - nasm 2.13.03 h62dcd97_1
    - perl 5.26.2.1 h0c8e037_0
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - ca-certificates
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - copy NUL checksum.txt
    - openssl sha256 checksum.txt
    - openssl ecparam -name prime256v1
    - python -c "import certifi; import ssl; import urllib.request as urlrq; urlrq.urlopen('https://pypi.org',
      context=ssl.create_default_context(cafile=certifi.where()))"
  requires:
    - certifi
    - python 3.7.*
    - six
about:
  description: 'OpenSSL is a robust, commercial-grade, full-featured Open Source Toolkit

    for the Transport Layer Security (TLS) protocol formerly known as the

    Secure Sockets Layer (SSL) protocol. The protocol implementation is based

    on a full-strength general purpose cryptographic library, which can also

    be used stand-alone.

    '
  dev_url: https://github.com/openssl/openssl
  doc_source_url: https://github.com/openssl/openssl/tree/OpenSSL_1_1_1-stable/doc
  doc_url: https://www.openssl.org/docs/man1.1.1/
  home: https://www.openssl.org/
  license: OpenSSL
  license_family: Apache
  license_file: LICENSE
  license_url: https://www.openssl.org/source/license.html
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2719f56f-cbd9-4c91-b4cf-96d2c49de67b
  recipe-maintainers:
    - carlodri
    - chenghlee
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/openssl-feedstock.git
  sha: 5d54c74b551094c0e4fdd2f5c39d99827874277a
