# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_5fhpy5y3hx\clone\recipe, last modified Thu Sep 22 06:16:15 2022
# ------------------------------------------------

package:
  name: zstandard
  version: 0.18.0
source:
  sha256: 0ac0357a0d985b4ff31a854744040d7b5754385d1f98f7145c30e02c6865cb6f
  url: https://pypi.io/packages/source/z/zstandard/zstandard-0.18.0.tar.gz
build:
  number: '0'
  string: py310h2bbff1b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.07.19 haa95532_0
    - certifi 2022.9.14 py310haa95532_0
    - cffi 1.15.1 py310h2bbff1b_0
    - libffi 3.4.2 hd77b12b_4
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.1.2 py310haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.10.4 hbb2ffb3_0
    - setuptools 63.4.1 py310haa95532_0
    - sqlite 3.39.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_3
  run:
    - cffi >=1.11
    - python >=3.10,<3.11.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - zstandard
  requires:
    - pip
about:
  description: 'This project provides Python bindings for interfacing with the

    Zstandard compression library. A C extension and CFFI interface are

    provided.

    '
  dev_url: https://github.com/indygreg/python-zstandard
  doc_source_url: https://github.com/indygreg/python-zstandard/tree/main/docs
  doc_url: https://github.com/indygreg/python-zstandard/blob/master/README.rst#python-zstandard
  home: https://github.com/indygreg/python-zstandard
  license: BSD-3-Clause
  license_file: LICENSE
  license_url: https://github.com/indygreg/python-zstandard/blob/main/LICENSE
  lisense_family: BSD
  summary: Zstandard bindings for Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5fe7d202-9997-4f64-9084-e087e1266a2d
  recipe-maintainers:
    - rmax
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/zstandard-feedstock.git
  sha: e6189e8e4ba3b1da6f8c80c1c4f154bbd7d22d29
